#!/bin/bash
declare -x ucpid=`adb shell ps | grep "$1" | grep -v "UCMobile:" | grep -v "Tool" | grep -v "UCMobile/" | grep -v ":" | grep -v " Z com" | grep -v "daemon"`
echo $ucpid
ucpid=`echo $ucpid | awk '{print $2}' `
echo $ucpid
ucpid="/data/local/tmp/gdbserver\ --attach\ \:5039\ $ucpid"
#ucpid="/data/local/tmp/gdbserver --attach :5039 $ucpid"

echo $ucpid
adb shell "su -c $ucpid"

