#!/usr/bin/python
import sys
import os
import time
import platform

argv = ""
platformArgv = ""
shell = "/Users/mamk/gdb/s2 "
platformArgv = " "

if len(sys.argv) == 1:
    argv = "."
else:
    for i in range(1, len(sys.argv)):
        argv += sys.argv[i] + " "

shell = shell + platformArgv + argv 

pid = os.fork()
if pid == 0:
    print shell
    os.system(shell)
else:
    time.sleep(1)
    
            
        
